version: 2
multi-ecosystem-groups:
  dependency-updates:
    schedule:
      interval: daily
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependency-updates
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
  # Python
  - package-ecosystem: uv
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependency-updates
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
  # Admin dashboard
  - package-ecosystem: bun
    directory: /apps/admin_dashboard
    patterns: ["*"]
    multi-ecosystem-group: dependency-updates
    cooldown:
      default-days: 7
    commit-message:
      prefix: ⬆
